export const copy = {
  'brand.name': 'Cermat',
  'brand.tagline': 'Cek keuangan kamu dalam 10 menit',

  'landing.hero.title': 'Aman gak kalau gw KPR, Gadai, atau Cicil?',
  'landing.hero.subtitle': 'Berapa max utang yang aman? Cek dalam 10 menit.',
  'landing.hero.trust': 'Tanpa daftar. Tanpa cloud.',

  'landing.cta.snapshot.label': 'Mulai dari Snapshot',
  'landing.cta.snapshot.body': 'Isi data kamu sendiri (5–10 menit).',
  'landing.cta.snapshot.action': 'Mulai',

  'landing.cta.demo.label': 'Coba dengan data contoh',
  'landing.cta.demo.body': 'Skip dulu, lihat tools-nya.',
  'landing.cta.demo.action': 'Coba',

  'footer.disclaimer':
    '100% client-side. Data kamu tetap di komputer kamu. Cermat bukan penasihat keuangan atau produk berizin.',

  'banner.simulation.disclaimer':
    'Hasil di sini cuma simulasi pakai data kamu. Cermat bukan penasihat keuangan atau produk berizin.',

  // ----- app shell -----
  'nav.track': 'Track',
  'nav.plan': 'Plan',
  'nav.decide': 'Decide',
  'nav.discover': 'Discover',
  'nav.soon': 'Soon',
  'nav.download.label': 'Unduh xlsx',
  'nav.download.empty': 'Tambah minimal 1 aset dulu',
  'nav.brand.subtitle': 'Cek Rupiah Mu Agar Teratur 💸',

  // ----- snapshot page -----
  'snapshot.title': 'Snapshot',
  'snapshot.section.penghasilan': 'Penghasilan',
  'snapshot.section.pengeluaran': 'Pengeluaran rutin',
  'snapshot.section.asetLikuid': 'Aset likuid',
  'snapshot.section.asetNonLikuid': 'Aset non-likuid',
  'snapshot.section.crypto': 'Crypto (live, by unit)',
  'snapshot.section.emas': 'Emas',
  'snapshot.section.cicilanAktif': 'Cicilan aktif',
  'snapshot.section.utangPribadi': 'Utang pribadi',
  'snapshot.section.gadai': 'Gadai',
  'snapshot.penghasilan.gajiLabel': 'Gaji Bersih',
  'snapshot.penghasilan.gajiHelp': 'Take-home pay setelah PPh21.',
  'snapshot.penghasilan.lainLabel': 'Penghasilan Lain',
  'snapshot.penghasilan.lainHelp': 'Sampingan, sewa, freelance, dll.',
  'snapshot.pengeluaran.pokok.label': 'Pokok/bulan',
  'snapshot.pengeluaran.pokok.help': 'Makan, transport, listrik, sewa — yang rutin tiap bulan.',
  'snapshot.pengeluaran.lifestyle.label': 'Lifestyle/bulan',
  'snapshot.pengeluaran.lifestyle.help': 'Hiburan, langganan, belanja non-pokok.',
  'snapshot.pengeluaran.note':
    'Cicilan jangan dimasukin di sini — diisi di "Cicilan aktif" biar gak double-count.',
  'snapshot.aset.kas': 'Tabungan / Kas',
  'snapshot.aset.deposito': 'Deposito',
  'snapshot.aset.reksaDana': 'Reksa Dana',
  'snapshot.aset.sbn': 'SBN / Obligasi',
  'snapshot.aset.properti': 'Properti',
  'snapshot.aset.kendaraan': 'Kendaraan',
  'snapshot.aset.pensiun': 'Dana pensiun',
  'snapshot.row.add': '+ Tambah',
  'snapshot.row.labelPlaceholder': 'Nama (opsional)',
  'snapshot.row.idrPlaceholder': 'Nilai',
  'snapshot.row.remove': 'Hapus',
  'snapshot.row.fxStale': '≈ kurs belum kebaca',
  'snapshot.emas.help':
    'Isi gram di kategori yang sesuai. Estimasi rate per gram pakai sumber publik (Pegadaian Digital untuk digital, Antam 1gr × kadar/karat untuk fisik & perhiasan). Yang lagi digadai diisi per kontrak di seksi Gadai.',
  'snapshot.emas.tertahanDerived': 'Tertahan: {grams} gram (dari {count} kontrak gadai)',
  'snapshot.emas.tertahanZero': 'Belum ada gadai aktif.',
  'snapshot.emas.staleRate': 'Live rate belum kebaca.',
  'snapshot.emas.totalLabel': 'Total nilai emas',
  'snapshot.emas.subtotal': '{grams} g × {rate}/g = {value}',
  'snapshot.emas.atHomeBreakdown': '{available}g di tangan, {pawned}g digadai (total {total}g)',
  'snapshot.emas.rateLine': 'Estimasi ~{rate}/g',
  'snapshot.emas.digital.label': 'Digital (Pegadaian / e-mas)',
  'snapshot.emas.digital.note': 'Pakai harga jual Pegadaian Digital langsung.',
  'snapshot.emas.fisik.label': 'Fisik (Antam batangan)',
  'snapshot.emas.fisik.note': 'Estimasi pakai harga Antam 1gr × 0.897 (spread buyback ~10%).',
  'snapshot.emas.perhiasan.label': 'Perhiasan',
  'snapshot.emas.perhiasan.note':
    'Estimasi pakai harga Antam dikali persentase kadar (18K/14K/10K).',
  'snapshot.emas.perhiasan.18K.label': '18 Karat (~75% emas)',
  'snapshot.emas.perhiasan.18K.note': '~59.5% Antam (range 57–62%).',
  'snapshot.emas.perhiasan.14K.label': '14 Karat (~58% emas)',
  'snapshot.emas.perhiasan.14K.note': '~45.5% Antam (range 43–48%).',
  'snapshot.emas.perhiasan.10K.label': '10 Karat (~42% emas)',
  'snapshot.emas.perhiasan.10K.note': '~37.5% Antam (range 35–40%).',

  // ----- crypto (dropdown + 4 input modes) -----
  'snapshot.crypto.help':
    'Pilih coin dari dropdown (top 52 di CoinGecko, bisa di-search) lalu pilih mode input — Unit (jumlah coin), IDR / USD / KRW (nilai dalam mata uang itu). Total selalu dikonversi ke IDR.',
  'snapshot.crypto.refresh': 'Refresh',
  'snapshot.crypto.refreshError': 'Gagal · klik ulang',
  'snapshot.crypto.refreshAria': 'Refresh harga crypto live',
  'snapshot.crypto.empty': 'Belum ada crypto. Klik "+ Tambah crypto" untuk mulai.',
  'snapshot.crypto.add': '+ Tambah crypto',
  'snapshot.crypto.remove': 'Hapus crypto',
  'snapshot.crypto.coinPlaceholder': 'Symbol coin (mis. BTC, ETH, XAUT)',
  'snapshot.crypto.coinAria': 'Symbol coin crypto',
  'snapshot.crypto.modeAria': 'Mode input crypto',
  'snapshot.crypto.modeUnit': 'Unit',
  'snapshot.crypto.modeIdr': 'IDR',
  'snapshot.crypto.modeUsd': 'USD',
  'snapshot.crypto.modeKrw': 'KRW',
  'snapshot.crypto.unitFallback': 'unit',
  'snapshot.crypto.ratePickCoin': 'Pilih coin dulu untuk lihat harga live.',
  'snapshot.crypto.rateStale': 'Live rate {sym} belum kebaca.',
  'snapshot.crypto.rateLine': '{rates} / 1 {sym}',
  'snapshot.crypto.idrStale': '≈ — (rate belum kebaca)',
  'snapshot.crypto.fxStale': '≈ — (kurs FX belum kebaca)',
  'snapshot.crypto.amountPlaceholder': 'Nilai',
  'snapshot.crypto.duplicateWarning':
    'Coin {sym} sudah dipakai di row lain. Hapus salah satu atau ubah biar gak double-count.',
  'snapshot.crypto.totalLabel': 'Total nilai crypto',

  // ----- cicilan -----
  'cicilan.add': '+ Tambah cicilan',
  'cicilan.quickadd.kpr': '+ KPR',
  'cicilan.quickadd.kpm': '+ KPM',
  'cicilan.quickadd.kk': '+ Kartu Kredit',
  'cicilan.quickadd.pinjol': '+ Pinjol',
  'cicilan.empty': 'Belum ada cicilan aktif.',
  'cicilan.field.label': 'Nama (mis. KPR BCA 2024)',
  'cicilan.field.tipe': 'Tipe',
  'cicilan.field.sisaPokok': 'Sisa pokok (IDR)',
  'cicilan.field.cicilan': 'Cicilan/bulan (IDR)',
  'cicilan.field.sukuBunga': 'Bunga (%/tahun)',
  'cicilan.field.tenorSisa': 'Sisa tenor (bulan)',
  'cicilan.field.jenisBunga': 'Jenis bunga',
  'cicilan.field.tanggal': 'Jatuh tempo (opsional)',
  'cicilan.warning.missingBunga': 'Isi bunga biar proyeksi prepay akurat.',
  'cicilan.warning.floatingNoBunga': 'Floating tanpa rate — proyeksi pakai rate default.',
  'cicilan.warning.overPenghasilan': 'Total cicilan lebih dari penghasilan — cek lagi datanya.',
  'cicilan.aggregate.total': 'Total cicilan/bulan',
  'cicilan.aggregate.pokok': 'Total sisa pokok',
  'cicilan.aggregate.biggest': 'Cicilan terbesar',

  // ----- utang pribadi (informal debt) -----
  'utangPribadi.help':
    'Pinjaman informal/non-bank: ke teman, keluarga, atau orang lain. Tetap masuk Net Worth & DAR; cicilan/bulan (kalau ada) masuk ke DSR.',
  'utangPribadi.empty': 'Belum ada utang pribadi.',
  'utangPribadi.add': '+ Tambah utang pribadi',
  'utangPribadi.row.remove': 'Hapus',
  'utangPribadi.field.label': 'Nama (mis. Pinjam ke Bro Andi)',
  'utangPribadi.field.sisaPokok': 'Sisa pokok (IDR)',
  'utangPribadi.field.cicilan': 'Cicilan/bulan (opsional)',
  'utangPribadi.field.tempo': 'Tempo (bulan, opsional)',
  'utangPribadi.field.tanggal': 'Jatuh tempo (opsional)',
  'utangPribadi.aggregate.total': 'Total utang pribadi',
  'utangPribadi.aggregate.cicilan': 'Total cicilan/bulan',

  // ----- gadai -----
  'gadai.empty': 'Belum ada kontrak gadai.',
  'gadai.add': '+ Tambah kontrak gadai',
  'gadai.row.remove': 'Hapus kontrak',
  'gadai.field.label': 'Nama kontrak (mis. Pegadaian Bandung 2024)',
  'gadai.field.jaminan': 'Jaminan',
  'gadai.field.tertahan': 'Berapa gram digadai',
  'gadai.field.piutang': 'Piutang gadai (IDR)',
  'gadai.field.bunga': 'Bunga (%/bulan)',
  'gadai.field.tempo': 'Tempo (bulan)',
  'gadai.field.tanggal': 'Jatuh tempo (opsional)',
  'gadai.field.asetRef': 'Aset yang dijaminkan',
  'gadai.field.asetRef.pick': 'Pilih aset...',
  'gadai.asetRef.empty.properti':
    'Belum ada properti di snapshot. Tambah dulu di Aset non-likuid → Properti.',
  'gadai.asetRef.empty.kendaraan':
    'Belum ada kendaraan di snapshot. Tambah dulu di Aset non-likuid → Kendaraan.',
  'gadai.emasRef.empty': 'Belum ada {jenis} di snapshot. Tambah dulu di seksi Emas.',
  'gadai.warning.overOwned':
    'Total digadai di kategori ini {pawned}g, lebih dari yang dimiliki {owned}g.',
  'gadai.aggregate.totalEmasGram': 'Total emas digadai',
  'gadai.aggregate.piutang': 'Total piutang',
  'gadai.aggregate.kontrak': 'Jumlah kontrak',
  'gadai.jaminan.emas.digital': 'Emas Digital',
  'gadai.jaminan.emas.fisikAntam': 'Emas Fisik (Antam)',
  'gadai.jaminan.emas.perhiasan18K': 'Emas Perhiasan 18K',
  'gadai.jaminan.emas.perhiasan14K': 'Emas Perhiasan 14K',
  'gadai.jaminan.emas.perhiasan10K': 'Emas Perhiasan 10K',
  'gadai.jaminan.properti': 'Properti (SHM/SHGB)',
  'gadai.jaminan.kendaraan': 'Kendaraan (BPKB)',
  'gadai.rasioTertahan': 'Rasio Tertahan',
  'gadai.zone.aman': 'Aman',
  'gadai.zone.waspada': 'Waspada',
  'gadai.zone.bahaya': 'Risiko Likuidasi',

  // ----- dashboard / metrics -----
  'metric.netWorth.label': 'Net Worth',
  'metric.modalSiap.label': 'Modal Siap Distribusi',
  'metric.modalSiap.advisory': 'Pertimbangkan keep dana darurat 3–6 bulan terpisah.',
  'metric.dsr.label': 'DSR',
  'metric.dar.label': 'DAR',
  'metric.runway.label': 'Runway',
  'metric.savingsRate.label': 'Savings Rate',
  'metric.safeHaven.label': 'Safe Haven',
  'metric.allocationDiscipline.label': 'Allocation Discipline',
  'metric.empty.dsr': 'Isi penghasilan dulu.',
  'metric.empty.dar': 'Isi aset dulu.',
  'metric.empty.runway': 'Isi pengeluaran dulu.',
  'metric.empty.savingsRate': 'Isi penghasilan dulu.',
  'metric.empty.safeHaven': 'Isi aset dulu.',
  'metric.empty.allocationDiscipline': 'Tambah saham + target bobot di panel Saham.',

  'pill.live': 'LIVE',
  'pill.estimasi': 'ESTIMASI',
  'pill.stale': 'STALE',

  'snapshot.section.saham': 'Saham',
  'snapshot.saham.help':
    'Per-emiten dengan harga live IDX. Set target bobot kalau mau ngeliat drift dari alokasi.',
  'snapshot.saham.empty': 'Belum ada saham. Tambah emiten pertama di bawah.',
  'snapshot.saham.add': '+ Tambah Saham',
  'snapshot.saham.tickerPlaceholder': 'BBCA',
  'snapshot.saham.tickerAria': 'Ticker IDX (4 huruf)',
  'snapshot.saham.lotLabel': 'Lot',
  'snapshot.saham.lotAria': 'Jumlah lot',
  'snapshot.saham.hargaRataRataLabel': 'Harga rata-rata',
  'snapshot.saham.hargaRataRataHelp': 'Cost basis per lembar. Dipakai kalau live + override gak ada.',
  'snapshot.saham.targetLabel': 'Target bobot (%)',
  'snapshot.saham.targetHelp': 'Optional. Tanpa target, drift gak keitung.',
  'snapshot.saham.overrideLabel': 'Override harga (manual)',
  'snapshot.saham.overrideHelp': 'Kosongin = pakai harga LIVE. Isi kalau live salah / stale.',
  'snapshot.saham.lastUpdated': 'Terakhir update {time}',
  'snapshot.saham.priceMissing': 'Harga live belum kebaca',
  'snapshot.saham.expand': 'Lihat detail',
  'snapshot.saham.collapse': 'Sembunyikan detail',
  'snapshot.saham.remove': 'Hapus saham',
  'snapshot.saham.totalLabel': 'Total Saham',
  'snapshot.saham.refresh': 'Refresh',
  'snapshot.saham.refreshError': 'Coba lagi',
  'snapshot.saham.refreshAria': 'Refresh harga saham',
  'snapshot.saham.driftSehat': 'Bobot mendekati target',
  'snapshot.saham.driftWaspada': 'Bobot mulai drift dari target',
  'snapshot.saham.driftBahaya': 'Bobot jauh dari target',
  'snapshot.saham.driftNoTarget': 'Belum ada target bobot',
  'snapshot.saham.lotsTargetLabel': 'Lots target',
  'snapshot.saham.lotsTargetHelp': 'Goal akumulasi lot. Drives progress bar — opsional.',
  'snapshot.saham.lotsProgress': 'Lots: {now} / {target}',
  'snapshot.saham.lastDivLabel': 'Last dividen / lembar',
  'snapshot.saham.lastDivHelp': 'Annual, IDR per lembar.',
  'snapshot.saham.yieldLabel': 'Yield %',
  'snapshot.saham.yieldHelp': 'Annual yield (0–100%). Dipakai kalau gak punya angka dividen literal.',
  'snapshot.saham.potentialDividend': 'Potential Dividend: {amount}/tahun',
  'snapshot.saham.dividendSection': 'Dividen (opsional)',
  'snapshot.saham.dividendModeLastDiv': 'Last div',
  'snapshot.saham.dividendModeYield': 'Yield %',
  'snapshot.saham.dividendModeAria': 'Pilih mode input dividen',

  'snapshot.penghasilan.dividenLabel': 'Estimasi Dividen Saham',
  'snapshot.penghasilan.dividenHint': 'Dihitung otomatis dari data saham kamu.',
  'snapshot.penghasilan.dividenAnnual': '≈ {amount}/tahun',

  'chart.allocation.title': 'Alokasi Saham',
  'chart.allocation.empty': 'Belum ada saham di portofolio.',
  'chart.allocation.legendTotal': 'Total',
  'chart.safeHaven.title': 'Safe Haven vs Growth',
  'chart.safeHaven.empty': 'Belum ada aset untuk dipetakan.',
  'chart.safeHaven.safe': 'Safe Haven',
  'chart.safeHaven.growth': 'Growth',
  'chart.safeHaven.safeDesc': 'Kas + Deposito + Reksa Dana + Emas',
  'chart.safeHaven.growthDesc': 'Saham + Crypto + Aset Non-Likuid',
  'chart.loading': 'Memuat chart…',

  'error.generic.title': 'Ada yang gak beres',
  'error.generic.body': 'Coba muat ulang halaman, atau balik ke beranda.',
  'error.generic.cta': 'Kembali ke beranda',
} as const

export type CopyKey = keyof typeof copy

export function t(key: CopyKey, vars?: Record<string, string | number>): string {
  const raw = copy[key]
  if (!vars) return raw
  return raw.replace(/\{(\w+)\}/g, (_, name: string) =>
    vars[name] !== undefined ? String(vars[name]) : `{${name}}`,
  )
}
